[workspace]
allow_dirty = true
git_release_name = "{{ package }}-v{{ version }}"
git_tag_name = "{{ package }}-v{{ version }}"
release_always = false

[[package]]
name = "napi-build"
release = false

[[package]]
name = "napi-sys"
release = false

[[package]]
name = "napi"
release = false

[[package]]
name = "napi-derive-backend"
release = false

[[package]]
name = "napi-derive"
release = false
