nodeLinker: node-modules

npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

yarnPath: .yarn/releases/yarn-4.17.0.cjs

npmPreapprovedPackages:
  - oxlint
  - '@oxlint/*'
  - oxc-parser
  - '@oxc-parser/*'
  - '@oxc-project/*'
  - emnapi
  - '@emnapi/*'
