import { UniArchsByPlatform, type Platform } from '../../utils/index.js'

import {
  assertBindingTargetIdentFree,
  BINDING_TARGET_STAMP_HELPER,
  NAPI_BINDING_TARGET_EXPORT,
  NAPI_BINDING_TARGET_STAMP_FN,
} from './binding-target.js'

const bindingHeader = `/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */
`

/**
 * One build-time-known `.node` artifact a `direct` loader may require.
 *
 * `platform` and `arch` use Node.js runtime names (`process.platform` /
 * `process.arch`), so the multi-target loader can key on them directly.
 */
export interface DirectLoaderCandidate {
  platform: string
  arch: string
  /** Relative `require` specifier, e.g. `./example.linux-x64-gnu.node`. */
  specifier: string
}

/**
 * Generate a deterministic CommonJS loader for one known `.node` artifact.
 *
 * Unlike the `node` loader in `js-binding.ts`, this performs no runtime
 * platform detection: no `process.platform`/`process.arch` checks, no
 * musl/glibc probing, no `child_process` usage, and no npm native package
 * fallback. The artifact is selected at build time.
 */
export function createDirectCjsBinding(
  artifactSpecifier: string,
  idents: string[],
  bindingTarget = 'native',
): string {
  assertBindingTargetIdentFree(idents)
  return `${bindingHeader}
const nativeBinding = require('${artifactSpecifier}')

${BINDING_TARGET_STAMP_HELPER}
// Keep the marker a statically visible CommonJS export for cjs-module-lexer
// (Node's CJS -> ESM named export detection), mirroring the node loader:
// the assignment target is this loader's own module.exports, and the alias
// below replaces it with the binding itself.
module.exports.${NAPI_BINDING_TARGET_EXPORT} = ${NAPI_BINDING_TARGET_STAMP_FN}(nativeBinding, '${bindingTarget}')
module.exports = nativeBinding
${idents
  .map((ident) => `module.exports.${ident} = nativeBinding.${ident}`)
  .join('\n')}
`
}

/**
 * ESM named-export block shared by the single and multi direct loaders.
 * Mirrors `createEsmBinding`: named exports when `idents` is non-empty,
 * otherwise a default export. Only artifact resolution differs.
 */
function createDirectEsmExports(idents: string[], bindingTarget: string) {
  const bindingTargetExport = `export const ${NAPI_BINDING_TARGET_EXPORT} = '${bindingTarget}'`
  return idents.length > 0
    ? `const { ${idents.join(', ')} } = nativeBinding
${idents.map((ident) => `export { ${ident} }`).join('\n')}
${bindingTargetExport}`
    : `export default nativeBinding
${bindingTargetExport}`
}

/**
 * Generate a deterministic ESM loader for one known `.node` artifact.
 *
 * Export semantics mirror `createEsmBinding`: named exports when `idents` is
 * non-empty, otherwise a default export. Only artifact resolution differs.
 */
export function createDirectEsmBinding(
  artifactSpecifier: string,
  idents: string[],
  bindingTarget = 'native',
): string {
  assertBindingTargetIdentFree(idents)
  return `${bindingHeader}
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

const nativeBinding = require('${artifactSpecifier}')

${createDirectEsmExports(idents, bindingTarget)}
`
}

/**
 * Group build-time-known artifacts by runtime key (`platform-arch`).
 *
 * Several artifacts may share one key (e.g. `linux-x64-gnu` and
 * `linux-x64-musl`): the loader tries them in this order until one loads, so
 * no musl/glibc probing, `child_process`, or filesystem reads are needed.
 * A `universal` binary loads on every arch of its platform and is offered
 * first on each, mirroring the node loader's darwin-universal-first order.
 * Insertion order follows the configured targets, keeping every CI job's
 * generated file identical.
 */
function groupDirectCandidates(
  candidates: DirectLoaderCandidate[],
): [key: string, specifiers: string[]][] {
  const groups = new Map<string, string[]>()
  const append = (key: string, specifier: string) => {
    const list = groups.get(key)
    if (list) {
      if (!list.includes(specifier)) {
        list.push(specifier)
      }
    } else {
      groups.set(key, [specifier])
    }
  }
  const prepend = (key: string, specifier: string) => {
    const list = groups.get(key)
    if (list) {
      if (!list.includes(specifier)) {
        list.unshift(specifier)
      }
    } else {
      groups.set(key, [specifier])
    }
  }
  for (const { platform, arch, specifier } of candidates) {
    if (arch === 'universal') {
      for (const uniArch of UniArchsByPlatform[platform as Platform] ?? [
        'x64',
        'arm64',
      ]) {
        prepend(`${platform}-${uniArch}`, specifier)
      }
    } else {
      append(`${platform}-${arch}`, specifier)
    }
  }
  return [...groups.entries()]
}

/**
 * Render the lookup table plus the tiny loader that reads it. Shared
 * verbatim by the CJS and ESM multi loaders (`require` is the CommonJS
 * global in one and a `createRequire` handle in the other). Node 12
 * compatible: no optional chaining, no nullish coalescing, no `node:`
 * scheme.
 */
function createDirectTableSource(candidates: DirectLoaderCandidate[]): string {
  const table = groupDirectCandidates(candidates)
    .map(
      ([key, specifiers]) =>
        `  '${key}': [${specifiers.map((specifier) => `'${specifier}'`).join(', ')}],`,
    )
    .join('\n')
  return `const __napiDirectTable = {
${table}
}

function __napiLoadDirect() {
  const runtimeKey = process.platform + '-' + process.arch
  const candidates = __napiDirectTable[runtimeKey]
  if (!candidates) {
    throw new Error('Unsupported platform/arch: ' + runtimeKey + ' (supported: ' + Object.keys(__napiDirectTable).join(', ') + ')')
  }
  let lastError = null
  for (let index = 0; index < candidates.length; index++) {
    try {
      return require(candidates[index])
    } catch (error) {
      lastError = error
    }
  }
  throw lastError
}

const nativeBinding = __napiLoadDirect()`
}

/**
 * Generate a small CommonJS loader covering several known `.node` artifacts
 * (typically every `napi.targets` entry, so each CI job reuses the identical
 * file). Selection is a `platform-arch` lookup table over build-time-known
 * filenames: no npm native package fallback, no `child_process`, no musl
 * probing, no WASI chain, no version checks, and no
 * `NAPI_RS_NATIVE_LIBRARY_PATH` override.
 */
export function createDirectMultiCjsBinding(
  candidates: DirectLoaderCandidate[],
  idents: string[],
  bindingTarget = 'native',
): string {
  assertBindingTargetIdentFree(idents)
  return `${bindingHeader}
${createDirectTableSource(candidates)}

${BINDING_TARGET_STAMP_HELPER}
// Keep the marker a statically visible CommonJS export for cjs-module-lexer
// (Node's CJS -> ESM named export detection), mirroring the node loader:
// the assignment target is this loader's own module.exports, and the alias
// below replaces it with the binding itself.
module.exports.${NAPI_BINDING_TARGET_EXPORT} = ${NAPI_BINDING_TARGET_STAMP_FN}(nativeBinding, '${bindingTarget}')
module.exports = nativeBinding
${idents
  .map((ident) => `module.exports.${ident} = nativeBinding.${ident}`)
  .join('\n')}
`
}

/**
 * Generate a small ESM loader covering several known `.node` artifacts.
 * Resolution is the same lookup table as `createDirectMultiCjsBinding`;
 * exports mirror `createEsmBinding`.
 */
export function createDirectMultiEsmBinding(
  candidates: DirectLoaderCandidate[],
  idents: string[],
  bindingTarget = 'native',
): string {
  assertBindingTargetIdentFree(idents)
  return `${bindingHeader}
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

${createDirectTableSource(candidates)}

${createDirectEsmExports(idents, bindingTarget)}
`
}
