import {
  WASI_FAMILY_TARGET,
  WASI_FLAVOR_TRIPLES,
  wasiLoaderSuffix,
} from '../../utils/index.js'

import { NAPI_BINDING_TARGET_EXPORT } from './binding-target.js'

/**
 * `exports` condition a consumer enables to select the threadless flavor of
 * the unified `<package>-wasm32-wasi` package statically: `node -C
 * wasi-threadless`, webpack `resolve.conditionNames`, Vite
 * `resolve.conditions`, esbuild `--conditions`, Rollup `exportConditions`.
 * Package-defined; Node's core resolver ignores it unless it is enabled.
 */
export const WASI_THREADLESS_CONDITION = 'wasi-threadless'

const [THREADED_FLAVOR, THREADLESS_FLAVOR] = WASI_FLAVOR_TRIPLES

/** File names of the unified package's Node dispatcher and its declaration. */
export function wasiDispatcherFileNames(binaryName: string) {
  const loaderSuffix = wasiLoaderSuffix(WASI_FAMILY_TARGET)
  return {
    entry: `${binaryName}.${loaderSuffix}.cjs`,
    typeDef: `${binaryName}.${loaderSuffix}.d.cts`,
  }
}

/**
 * Node.js entry of the unified WASI package, which carries both flavors.
 *
 * Selection order: a `NAPI_RS_WASI_FLAVOR` pin loads exactly that flavor and
 * never crosses into the other; otherwise the threaded flavor is loaded first
 * and the threadless flavor is the fallback when the threaded loader throws
 * while loading or instantiating. A consumer who resolved the package with
 * the {@link WASI_THREADLESS_CONDITION} condition never reaches this file.
 *
 * Every branch assigns `module.exports = require('<literal>')`, and the last
 * such statement in source order re-exports the threadless loader. That is
 * what `cjs-module-lexer` — Node's CJS -> ESM named export detection — reads
 * as this module's re-export target, so `import { name } from
 * '<package>-wasm32-wasi'` links against the flavor loaders' statically
 * visible export lists; both flavors export the same names. The loaded flavor
 * reports itself through the loader's own `__napiBindingTarget` export, which
 * the re-export carries through unchanged.
 */
export function createWasiDispatcher(binaryName: string): string {
  const threadedLoader = `./${binaryName}.${wasiLoaderSuffix(THREADED_FLAVOR)}.cjs`
  const threadlessLoader = `./${binaryName}.${wasiLoaderSuffix(THREADLESS_FLAVOR)}.cjs`
  return `/* eslint-disable */
/* auto-generated by NAPI-RS */

// Node.js entry of the unified WASI package. It ships both WASI flavors:
//   ${THREADED_FLAVOR}  ${threadedLoader}
//   ${THREADLESS_FLAVOR}          ${threadlessLoader}
// NAPI_RS_WASI_FLAVOR pins one flavor and never crosses into the other.
// Otherwise the threaded flavor is loaded first and the threadless flavor
// is the fallback when the threaded loader fails to load or instantiate.
// Resolving this package with the "${WASI_THREADLESS_CONDITION}" exports
// condition (node -C ${WASI_THREADLESS_CONDITION}) selects the threadless
// flavor before this file runs.

const __napiWasiFlavors = ['${THREADED_FLAVOR}', '${THREADLESS_FLAVOR}']
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', ') +
      (__napiWasiFlavor === '${WASI_FAMILY_TARGET}'
        ? '. "${WASI_FAMILY_TARGET}" names the WASI target family, not one flavor; pin one of the flavors listed above instead.'
        : ''),
  )
}

if (__napiWasiFlavor === '${THREADED_FLAVOR}') {
  module.exports = require('${threadedLoader}')
} else if (__napiWasiFlavor === '${THREADLESS_FLAVOR}') {
  module.exports = require('${threadlessLoader}')
} else {
  let __napiThreadedError = null
  try {
    module.exports = require('${threadedLoader}')
  } catch (err) {
    __napiThreadedError = err
  }
  if (__napiThreadedError !== null) {
    try {
      module.exports = require('${threadlessLoader}')
    } catch (err) {
      const error = new Error(
        'Failed to load the WASI binding: the ${THREADED_FLAVOR} flavor failed to load, and so did the ${THREADLESS_FLAVOR} fallback. Set NAPI_RS_WASI_FLAVOR to one flavor to see its own error.',
      )
      // assign instead of the \`new Error(message, { cause })\` options form,
      // which Node < 16.9 silently ignores
      error.cause = err
      error.errors = [__napiThreadedError, err]
      throw error
    }
  }
}
`
}

export interface WasiDispatcherTypeDefOptions {
  /**
   * Whether the flavor declarations export by assignment (`export = binding`,
   * what a build without `napi-derive`'s `type-def` feature emits). Such a
   * module cannot be the target of `export *` (TS2498), so the dispatcher
   * declaration exports by assignment too.
   */
  exportsByAssignment?: boolean
}

/**
 * Declaration for {@link createWasiDispatcher}.
 *
 * Re-exports one flavor's declarations — the two flavors declare the same
 * surface — and widens `__napiBindingTarget` to the union of both flavor
 * identities. A local export wins over a name an `export *` would bring in,
 * so the explicit declaration is what consumers see.
 */
export function createWasiDispatcherTypeDef(
  binaryName: string,
  options: WasiDispatcherTypeDefOptions = {},
): string {
  const threadedLoader = `./${binaryName}.${wasiLoaderSuffix(THREADED_FLAVOR)}.cjs`
  const header = `/* auto-generated by NAPI-RS */
/* eslint-disable */
`
  if (options.exportsByAssignment) {
    return `${header}
declare const __napiWasiBinding: typeof import('${threadedLoader}')
export = __napiWasiBinding
`
  }
  return `${header}
export * from '${threadedLoader}'

/**
 * Which WASI flavor the dispatcher loaded: \`'${THREADED_FLAVOR}'\` by
 * default, \`'${THREADLESS_FLAVOR}'\` when pinned through \`NAPI_RS_WASI_FLAVOR\`
 * or when the threaded flavor failed to load.
 */
export declare const ${NAPI_BINDING_TARGET_EXPORT}: '${THREADED_FLAVOR}' | '${THREADLESS_FLAVOR}'
`
}
