window.BENCHMARK_DATA = {
  lastUpdate: 1642486932975,
  repoUrl: 'https://github.com/napi-rs/napi-rs',
  entries: {
    Benchmark: [
      {
        commit: {
          author: {
            email: 'lynweklm@gmail.com',
            name: 'LongYinan',
            username: 'Brooooooklyn',
          },
          committer: {
            email: 'noreply@github.com',
            name: 'GitHub',
            username: 'web-flow',
          },
          distinct: true,
          id: 'd85cbfd926244be4f536963af0282bc0a2042cd2',
          message:
            'Merge pull request #1039 from napi-rs/musl-zig-cross\n\nMusl zig cross',
          timestamp: '2022-01-18T14:12:19+08:00',
          tree_id: '69af469c1835a3cb40ed08c4473f5cd07822b4cb',
          url: 'https://github.com/napi-rs/napi-rs/commit/d85cbfd926244be4f536963af0282bc0a2042cd2',
        },
        date: 1642486931506,
        tool: 'benchmarkjs',
        benches: [
          {
            name: 'noop#napi-rs',
            value: 43569890,
            range: '±0.69%',
            unit: 'ops/sec',
            extra: '86 samples',
          },
          {
            name: 'noop#JavaScript',
            value: 711826201,
            range: '±0.6%',
            unit: 'ops/sec',
            extra: '89 samples',
          },
          {
            name: 'Plus number#napi-rs',
            value: 14398545,
            range: '±0.88%',
            unit: 'ops/sec',
            extra: '87 samples',
          },
          {
            name: 'Plus number#JavaScript',
            value: 718034345,
            range: '±0.74%',
            unit: 'ops/sec',
            extra: '87 samples',
          },
          {
            name: 'Create buffer#napi-rs',
            value: 296176,
            range: '±10.01%',
            unit: 'ops/sec',
            extra: '63 samples',
          },
          {
            name: 'Create buffer#JavaScript',
            value: 1436644,
            range: '±4.28%',
            unit: 'ops/sec',
            extra: '78 samples',
          },
          {
            name: 'createArray#createArrayJson',
            value: 34132,
            range: '±1.03%',
            unit: 'ops/sec',
            extra: '86 samples',
          },
          {
            name: 'createArray#create array for loop',
            value: 6179,
            range: '±0.86%',
            unit: 'ops/sec',
            extra: '82 samples',
          },
          {
            name: 'createArray#create array with serde trait',
            value: 6186,
            range: '±0.9%',
            unit: 'ops/sec',
            extra: '87 samples',
          },
          {
            name: 'getArrayFromJs#get array from json string',
            value: 14088,
            range: '±0.94%',
            unit: 'ops/sec',
            extra: '88 samples',
          },
          {
            name: 'getArrayFromJs#get array from serde',
            value: 8406,
            range: '±0.91%',
            unit: 'ops/sec',
            extra: '86 samples',
          },
          {
            name: 'getArrayFromJs#get array with for loop',
            value: 10289,
            range: '±0.77%',
            unit: 'ops/sec',
            extra: '88 samples',
          },
          {
            name: 'Get Set property#Get Set from native#u32',
            value: 330758,
            range: '±5.61%',
            unit: 'ops/sec',
            extra: '71 samples',
          },
          {
            name: 'Get Set property#Get Set from JavaScript#u32',
            value: 303320,
            range: '±5.12%',
            unit: 'ops/sec',
            extra: '75 samples',
          },
          {
            name: 'Get Set property#Get Set from native#string',
            value: 324634,
            range: '±4.8%',
            unit: 'ops/sec',
            extra: '70 samples',
          },
          {
            name: 'Get Set property#Get Set from JavaScript#string',
            value: 306506,
            range: '±4.93%',
            unit: 'ops/sec',
            extra: '74 samples',
          },
          {
            name: 'Async task#spawn task',
            value: 29896,
            range: '±2.41%',
            unit: 'ops/sec',
            extra: '67 samples',
          },
          {
            name: 'Async task#ThreadSafeFunction',
            value: 371,
            range: '±3.21%',
            unit: 'ops/sec',
            extra: '67 samples',
          },
          {
            name: 'Async task#Tokio future to Promise',
            value: 23129,
            range: '±2.15%',
            unit: 'ops/sec',
            extra: '79 samples',
          },
          {
            name: 'Query#query * 100',
            value: 1663,
            range: '±1.83%',
            unit: 'ops/sec',
            extra: '81 samples',
          },
          {
            name: 'Query#query * 1',
            value: 20854,
            range: '±1.59%',
            unit: 'ops/sec',
            extra: '76 samples',
          },
        ],
      },
    ],
  },
}
