window.BENCHMARK_DATA = {
  lastUpdate: 1637855270833,
  repoUrl: 'https://github.com/napi-rs/napi-rs',
  entries: {
    Benchmark: [
      {
        commit: {
          author: {
            email: 'lynweklm@gmail.com',
            name: 'LongYinan',
            username: 'Brooooooklyn',
          },
          committer: {
            email: 'lynweklm@gmail.com',
            name: 'LongYinan',
            username: 'Brooooooklyn',
          },
          distinct: true,
          id: 'e6f341f6323ff9bfdb8c99989233e302002802be',
          message: 'chore: add example for return this',
          timestamp: '2021-11-25T23:42:40+08:00',
          tree_id: 'ff2a65bed6a4ff9270fbb26304a2d5fa7fb30398',
          url: 'https://github.com/napi-rs/napi-rs/commit/e6f341f6323ff9bfdb8c99989233e302002802be',
        },
        date: 1637855268999,
        tool: 'benchmarkjs',
        benches: [
          {
            name: 'noop#napi-rs',
            value: 47771110,
            range: '±1.03%',
            unit: 'ops/sec',
            extra: '87 samples',
          },
          {
            name: 'noop#JavaScript',
            value: 688364437,
            range: '±1.01%',
            unit: 'ops/sec',
            extra: '86 samples',
          },
          {
            name: 'Plus number#napi-rs',
            value: 15984816,
            range: '±1.06%',
            unit: 'ops/sec',
            extra: '89 samples',
          },
          {
            name: 'Plus number#JavaScript',
            value: 693250423,
            range: '±0.99%',
            unit: 'ops/sec',
            extra: '85 samples',
          },
          {
            name: 'Create buffer#napi-rs',
            value: 348007,
            range: '±9.02%',
            unit: 'ops/sec',
            extra: '59 samples',
          },
          {
            name: 'Create buffer#JavaScript',
            value: 1502400,
            range: '±4.19%',
            unit: 'ops/sec',
            extra: '76 samples',
          },
          {
            name: 'createArray#createArrayJson',
            value: 34988,
            range: '±0.95%',
            unit: 'ops/sec',
            extra: '88 samples',
          },
          {
            name: 'createArray#create array for loop',
            value: 6105,
            range: '±1.1%',
            unit: 'ops/sec',
            extra: '86 samples',
          },
          {
            name: 'createArray#create array with serde trait',
            value: 6072,
            range: '±1.05%',
            unit: 'ops/sec',
            extra: '88 samples',
          },
          {
            name: 'getArrayFromJs#get array from json string',
            value: 14340,
            range: '±1.23%',
            unit: 'ops/sec',
            extra: '86 samples',
          },
          {
            name: 'getArrayFromJs#get array from serde',
            value: 8397,
            range: '±2%',
            unit: 'ops/sec',
            extra: '86 samples',
          },
          {
            name: 'getArrayFromJs#get array with for loop',
            value: 11313,
            range: '±0.91%',
            unit: 'ops/sec',
            extra: '89 samples',
          },
          {
            name: 'Get Set property#Get Set from native#u32',
            value: 351885,
            range: '±5.01%',
            unit: 'ops/sec',
            extra: '75 samples',
          },
          {
            name: 'Get Set property#Get Set from JavaScript#u32',
            value: 317506,
            range: '±4.54%',
            unit: 'ops/sec',
            extra: '79 samples',
          },
          {
            name: 'Get Set property#Get Set from native#string',
            value: 320114,
            range: '±5.18%',
            unit: 'ops/sec',
            extra: '71 samples',
          },
          {
            name: 'Get Set property#Get Set from JavaScript#string',
            value: 285885,
            range: '±4.9%',
            unit: 'ops/sec',
            extra: '79 samples',
          },
          {
            name: 'Async task#spawn task',
            value: 33144,
            range: '±2.83%',
            unit: 'ops/sec',
            extra: '74 samples',
          },
          {
            name: 'Async task#ThreadSafeFunction',
            value: 398,
            range: '±2.95%',
            unit: 'ops/sec',
            extra: '64 samples',
          },
          {
            name: 'Async task#Tokio future to Promise',
            value: 20312,
            range: '±3.26%',
            unit: 'ops/sec',
            extra: '70 samples',
          },
          {
            name: 'Query#query * 100',
            value: 1767,
            range: '±1.14%',
            unit: 'ops/sec',
            extra: '85 samples',
          },
          {
            name: 'Query#query * 1',
            value: 21483,
            range: '±3.2%',
            unit: 'ops/sec',
            extra: '76 samples',
          },
        ],
      },
    ],
  },
}
