/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Counter {
  constructor(initial?: number | undefined | null)
  increment(): number
  get value(): number
}

/** Add two numbers. */
export declare function add(a: number, b: number): number

export declare function describePerson(person: Person): string

/** A simple greeting function. */
export declare function greet(name: string): string

export interface Person {
  name: string
  age: number
}

export declare const enum Status {
  Active = 0,
  Inactive = 1,
  Pending = 2
}
