/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function startRetentionProbe(callback: () => void, scenario: string, enteredPath: string, releasePath: string, completedPath: string): void
